### ISSUE TITLE
README doesn't address the `if let` option

### ISSUE THREAD

**Issue by ssokolow** [neosmart/ignore-result#1]
Currently, the README makes the following false dichotomy:

> So you can either write this:
> 
> ```rust
> let foo = something_import();
> if foo.is_err() {
>     match cleanup() {
>         _ => {}
>     };
> 
>     return foo;
> }
>```
> 
> Or use this crate and write this instead:
> 
> ```rust
> use ignore_result::Ignore;
> 
> if foo.is_err() {
>     cleanup.ignore();
>     return foo;
> }
>```
> 
> and be on your merry way.

This ignores the more concise equivalent to that `match` block offered by the core language:

```rust
let foo = something_import();
if foo.is_err() {
    let _ = cleanup();
    return foo;
}
```

`let _ =` is the generic, built-in, whole-language equivalent to your `.ignore()` that works on *all* types and functions annotated with [`#[must_use]`](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute).

> Note: It is idiomatic to use a [let statement](https://doc.rust-lang.org/reference/statements.html#let-statements) with a pattern of `_` when a must-used value is purposely discarded.

Because `_` is the empty/match-all pattern, not a variable name, it doesn't assign a variable and hold the value until the end of the scope the way something like `let _unused = cleanup();` would. 

(`let` is still a pattern match, it's just limited to irrefutable patterns, unlike `if let` and `match`. That's how things like `let (x, y, z) = a;` tuple unpacking work and why `let (x, _, _) = a;` doesn't give you an error about using the same variable name multiple times.)

...and, to be honest, the README not acknowledging that option makes its creators look either deceptive, unwilling to do basic research, or incompetent.

**Comment by mqudsi** [comment]
This is an old crate and you probably shouldn't be using it. I'm not sure how you arrived here, but we use and recommend `let _ = ...` now.

**Comment by ssokolow** [comment]
It showed up in a crates.io/lib.rs search and you haven't pushed an update to add "This is an old crate and you probably shouldn't be using it. I'm not sure how you arrived here, but we use and recommend `let _ = ...` now." to the `README` for novices who don't know any better.
